### ISSUE TITLE
TSC

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/TSC#1]
If you are interested in joining a TSC, please respond to this issue.

**Comment by jlaura** [comment]
I am.

**Comment by rbeyer** [comment]
I am.

**Comment by jessemapel** [comment]
Ever since I started at the federal government, I always wanted to a bureaucrat, so I am interested.

**Comment by thareUSGS** [comment]
While not officially raising my hand for the TSC, I would be happy to report community sensor model (CSM) working group and open geospatial consortium (OGC) updates to the TSC. Not sure those would need a TSC-related working group just yet. For example, recent topics that the TSC should consider.

**OGC** (interoperability/web):
- GeoTiff. spec v1 is nearing completion. This is mainly to officially solidify the current version already in the wild so "v2" can be started.
- GeoFITS (geospatial addition to FITS) has been proposed and an implementation in GDAL has been released by Chiara M. and is ready for testing. https://epn-vespa.github.io/geofits/
- GeoCSV format, which should allow for GIS vector archival in PDS should be ready for testing in February. 

The TSC should consider replacing previous format conversion methods (QT's [jpeg,png,tif], LibTIFF, FITS, maybe even VICAR) in favor of supporting the GDAL library. If capabilities are lacking, fix them in GDAL.
   
- Work on Proj (by Even R.) is progressing well: https://proj4.org/community/rfc/rfc-2.html?highlight=gdal# . 

The TSC might consider a method to integrate with this projection engine. There still may need to be some planetary testing required (e.g. oc/ographic).

**CSM** (standardized senor model implementation):
- The CSM WG continues to look for a more official release home for the standard (most likely to be NGA).

**Comment by jlaura** [comment]
@michaelaye Is that yo! you signing up?

**Comment by michaelaye** [comment]
@jlaura i thought that was still pending a review/evaluation somewhere? Imagine you get 100 sign-ups? ;) I'm not sure if I'm qualified for all topics that seem to be in the responsibility list for TSC members (see my PR for the next meeting), but if you'll have me, I'm in. ;)

**Comment by SgStapleton** [comment]
Count me in!

**Comment by USGSsakins** [comment]
Please include me in future TSC meetings.

**Comment by AndrewAnnex** [comment]
Please add me! thanks!

**Comment by victoronline** [comment]
I am interested. Please add me!

**Comment by jessemapel** [comment]
@AndrewAnnex @victoronline if you could, please join us at the next TSC meeting, April 9th. Meeting agenda is [here](https://github.com/USGS-Astrogeology/TSC/blob/master/meetings/2019-04-09.md)

**Comment by jlaura** [comment]
I am going to close this issue. We can either re-open on the new repo or we can simply have interested members start attending TSC monthly meetings and then move from there with the joining procedure (as documented).
