### ISSUE TITLE
Postpone next TSC meeting until shutdown is over

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/TSC#15]
Do to the limited non-USGS TSC participation at this time, having the next scheduled meeting (TSC/meetings/2019-01-22.md) would be of limited usefulness.  When the shutdown ends, we can reschedule the January TSC meeting.  Let's hope it is just rescheduled to February.

**Comment by jlaura** [comment]
:+1: Thank you for catching this!
