### ISSUE TITLE
Potential TSC Scope and Organization change

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/TSC#28]
At LPSC, there were some informal discussions (at different times) about applying two potential major changes to the TSC, a 'scope' change and an 'organization' change.  This issue is meant to lay out an understanding of those conversations, and see if we are all on the same page, and then if we are--what to do about it.

# Change of Scope

Firstly, the TSC, as our Charter lays out, has a 'scope' that is limited to ASC software (including but not limited to ISIS), and we primarily provide guidance (steering) for software projects that the ASC has requested our opinions on (but not all ASC software).  They are free to disregard that advice, since they--not the TSC--own those projects.

To a limited extent at our last TSC meeting, and to a greater extent during conversations at LPSC, some of us think that there might be a greater role for the TSC to play on the larger stage of planetary science software in two areas:

## More Projects to Advise

Could the 'scope' of applicability of the TSC be widened to any software project that wants our advice (instead of just selected ASC projects)?  

This isn't too crazy, its just widening our scope to allow any project that wants our advice or guidance to do so.  There's lots of potential implementation details (do we keep a 'list' of projects that meet our guidelines, or does it not matter), but this is about concept, so let's not go down that rabbit-hole quite yet.  Any project or person can request an agenda item, and if it gets merged into the agenda, we talk about it.

## Project Stewardship

Could we act as a 'steward' for those software projects that wanted it?

So the above scope change about 'more projects' simply allows additional projects to come to our table and get advice, but the TSC doesn't actually own those projects, their ownership remains outside of the TSC.  Which is fine, some organizations or individuals want or need to retain control of their projects, but want community input.  However, other people might want to place the management of their software into 'stewardship.'  They want the software to live on and grow, but acknowledge that they might not be able to do that on their own effectively, or we as a TSC may determine that there is a piece of unmaintained software that has utility to our community that could use some help.  In this mode, the TSC would host the software under an organizational GitHub repo, and invite the community to help maintain the software (according to TSC guidelines).  The intent is not for the TSC to become the maintainers (that could potentially be a ton of work), but to provide a 'public space' with some minimal supervision to allow the community to contribute to worthwhile projects that have been put under TSC stewardship for the good of the community.  Again, lots of implementation details here, but let's keep thinking about this at a high level.

# Change of organization

The second major change is a corollary of the first.  If any of the above changes are made to the scope of the TSC, then the appropriate 'place' for the TSC to organize itself probably isn't under the USGS-Astrogeology GitHub repo.  Since the 'scope' would widen out beyond just ASC software, then organizing under their GitHub umbrella (while a fine place to be given the current scope, and a wonderful place to have incubated if we decide to change) may not be the best place for a community group to be seen by the community as independent of any particular institution.

We chatted a little at LPSC about possibilities.  There was some discussion about finding a different organization's umbrella to get underneath.  The issue is that while existing organizations like scholarly societies (e.g. the [DPS](http://dps.aas.org)) or other community groups (e.g. [OpenPlanetary](http://openplanetary.org)) might have some similar goals or inhabit adjacent conceptual spaces, none of them seems like quite the right fit (but maybe we haven't found the right one, or talked it out enough).  So maybe the TSC just spins itself out as a new organization and we see where it goes?

# Summary

These two potential major changes are a little scary, because they have the potential to invite a lot more work, but the hope is that they would also invite more participation from the community, and result in an even stronger group of people for which to talk about software issues and topics relevant to planetary science, and a group to help guide ideas about software development in this space, and act as a stewardship organization for pieces of code that might need it.

**Comment by jessemapel** [comment]
All of this sounds good to me :+1:. One thing I would note, is that we would invite maintainers of any packages that want "advisement" or "stewardship" to join the TSC.

A critical component of growing the TSC into a resource for the broader community is growing the TSC membership to include more of the community.

Once we have more people involved, we should add back the clause about what percentage of the TSC can belong to a single organization.

**Comment by jessemapel** [comment]
The [Project Lifecycle](https://github.com/USGS-Astrogeology/TSC/blob/master/Project-Lifecycle.md) document describes a process for integrating new projects, which requires a certain leadership group for the project. This should help alleviate work for the TSC.

**Comment by jlaura** [comment]
Let's discuss this at the next TSC meeting. :+1: here from me. We should talk about where to host this, etc. Then we can go from there.

**Comment by rbeyer** [comment]
I'm not sure how the RFC template thing has anything to do with this Issue.  Furthermore, I'd like to keep this Issue open for comment until our next TSC meeting, and then either resolve it at the next TSC meeting, or table it for more discussion.

**Comment by jessemapel** [comment]
@rbeyer looks like, @jlaura made a typo in his PR, #28 instead of #29

**Comment by jlaura** [comment]
:+1: #29

**Comment by AndrewAnnex** [comment]
I had a conversation with Austin Godber about the planetarypy github organization https://github.com/orgs/planetarypy/ possibly serving this role however some barn raising is needed for this. Currently a telecon is being organized on the OpenPlanetary slack but should be expanded to include more interested parties

**Comment by michaelaye** [comment]
We don’t need it though, Austin was less cooperative the last time I had that conversation. We can stay in the openplanetary github org if we decide to go that route. I have nothing against calling the python package the same, even so that’s independent of the org name.

**Comment by rbeyer** [comment]
At our [9 April 2019 meeting](https://github.com/USGS-Astrogeology/TSC/blob/master/meetings/2019-04-09.md), we voted 'yes' on both the change of scope and the change of organization.
