### ISSUE TITLE
missed meeting!

### ISSUE THREAD

**Issue by AndrewAnnex** [USGS-Astrogeology/TSC#40]
sorry for missing the meeting, I forgot to set a reminder for myself. Any chance we could have a short meeting to discuss the issues I was referenced in the meeting notes sooner than next month?

**Comment by rbeyer** [comment]
Sure, but then you're on the hook to find a time that we can all meet, set an agenda (if you think you need one).  The Tuesday at noon MST seems to work for folks, so you could target one or more of those between now and the next meeting.  Might be easier to just open an issue and have us type about it, but up to you.

**Comment by AndrewAnnex** [comment]
ok I will look into that later today, the 16th or 23rd would be fine for me at the moment but I will confirm later.
