### ISSUE TITLE
New Name Ideas

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/TSC#43]
Following on our [2019-04-09 meeting](https://github.com/USGS-Astrogeology/TSC/blob/master/meetings/2019-04-09.md) where we decided we would widen our scope, we need a name to organize all of these shenanigans under.

A potentially relevant example is 'Apache'.  So the 'top level' name, if you will, is 'Apache' or 'Apache Software', and there are a multitude of projects, all written in different languages (they even have one named Isis!) that are 'Apache Projects.'  There is also a very formal 'Apache Software Foundation' which is the thing that the people are organized under.

- The *thing* is 'Apache' or 'Apache Software.'
- The human beings that guide *the thing* are members of the 'Apache Software Foundation.'
- And the various software projects are under the 'Apache Software' umbrella.

So we need a name for our *thing*.
- We would be members of the '*thing* Steering Committee' (or some other moniker if we don't like the echo from TSC--we certainly aren't a Foundation).
- And then various projects would be under our new *thing* umbrella.  Some of those projects would simply be listed (like ISIS) since the authors wish to maintain control, and other projects would fall under our stewardship, like Spicepy, or even PlanetaryPy.  These would either be referenced from our main location (some website or just a GitHub site) like ISIS (which has its own repo) or would be under our main GitHub repo.

So, suggest names for *the thing* and any other name-relevant bits you can think of.  Hopefully we'll have enough of these so that we can have a reasonable discussion at our May meeting.

**Comment by rbeyer** [comment]
Thing: Planetary Software

People: Planetary Software Steering Committee, Planetary Software People?

Generic, I know.

**Comment by AndrewAnnex** [comment]
Open Planetary Consortium?
The Planetary Consortium?
The Open Planetary Consortium?

possibly not in line with the first post

**Comment by rbeyer** [comment]
Pursuant to our discussion at the [2019-05-14 meeting](https://github.com/USGS-Astrogeology/TSC/blob/master/meetings/2019-05-14.md), we have settled on 'Planetary Software' for the name of the new venture, and are planning to use the term 'Planetary Software Steering Committee' to refer to the people.
