### ISSUE TITLE
andrewannex as a member of the TSC

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/TSC#45]
This is an asynchronous vote for having @andrewannex join the TSC.

**Comment by jlaura** [comment]
@victoronline Can you accept joining (git email) and then we can assign you and you can vote. Also, this issue will be open for 7 days. Please vote during that time.

**Comment by victoronline** [comment]
Done. How do we vote? Do I just say yay or nay? Is there an official voting emoji?

**Comment by jlaura** [comment]
I think a +1 would be cool(?)....quite formal.

**Comment by victoronline** [comment]
+1

**Comment by michaelaye** [comment]
+1

**Comment by jessemapel** [comment]
:+!:

**Comment by jessemapel** [comment]
@ALL I think everyone has voted in favor of Andrew joining. I'm going to close this at the end of the week unless someone is against it. After that we'll get Andrew added officially.

**Comment by AndrewAnnex** [comment]
@jessemapel I think I am at this point added to the club. Unfortunately, I probably won't be able to attend the next scheduled meeting on the 14th, but I might be able to attend the first half hour or so of the meeting.

**Comment by jessemapel** [comment]
@AndrewAnnex That shouldn't be a problem.

**Comment by jessemapel** [comment]
apologies for being super slow on this, I've added Andrew as an admin to the repo and put in a PR for his addition to the membership list.
