### ISSUE TITLE
Location of Documents for Governance and non-Governance

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/TSC#5]
This is related to the discussion on #3. We have this repo where TSC related documents are being stored. Where do we put things that are less organizational and more actionable?

For example, the [ISIS3 Release RoadMap](https://github.com/USGS-Astrogeology/ISIS3/wiki/Release-Road-Map) is a draft roadmap for the release of the ASC Core (ISIS3). I would suggest that a document like this live in the ISIS3 repository. In fact, any of these non-governance, actionable documents should live in the repositories that they are associated with. Thoughts?

**Comment by jessemapel** [comment]
RFC#1 on the ISIS repo is now closed. I've left it up on the wiki and just moved it in the side-bar to an `Archived RFCs` list. For this RFC I think it's sufficient to just have that there as record of what was decided and the issue with comments people had.

For RFC#2, I think if it's accepted, the release policy needs to be written as a separate document and stored on the Wiki. The RFC text can remain and just be archived, but the release policy document needs to live on.

**Comment by jlaura** [comment]
@all I am going to close this. I think we have a better handle (after last night) on where some of the boundaries exist. This is a non-issue at this time.
