### ISSUE TITLE
ISIS3 and VICAR integration thoughts for the TSC

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/TSC#51]
**Motivation**: 
The goal of a better integrated VICAR/ISIS3 would expand both software’s capabilities across Planetary and Earth disciplines, simplify their use, help to modernize the computing architectures, reduce software maintenance and Open Source support costs, and provide a new/improved software foundation for future users and data processing.
- The VICAR and ISIS software represent decades of dedicated NASA and USGS mission activities and untold technological developments and achievements.
- There are no commercial equivalents to these critical resources.
- The goal is to integrate, then simplify the complex process of Planetary and Earth calibration, registration, and image processing, and make it accessible to researchers, universities and the public.

**Alignment with Strategic Plan**:
- Goal 1: Reduce mission operations cost and risk.
- Goal 2: Leverage and be consistent with technological advances.
- Goal 3: Broaden use-cases to support to future missions (in-situ and orbital)
- Goal 4: Employ a principled architectural approach

**Task Descriptions**
- Coordinate NASA/USGS inter-agency management.
- Coordinate NASA/JPL and USGS/ASC **Technical Steering Committee (TSC)**.
- Develop and support an active (Open Source) user community
- JPL tasks include Integrating VICAR components (Mainline; Mars; AFIDS/Geocal; NEST), integrating with ISIS3, and coordinating with PDS.
- USGS/ASC tasks include better integrating with VICAR and building an integrated open user support infrastructure.
- Key joint activities include designing and developing integrated Use-Cases; modernizing, maintaining, and supporting software. 
- Plan for future enhancements (e.g., 3D Visualization, cloud services, other integrations).

**Implementation Approach**: 
- Integrate VICAR/ISIS file formats (allow for better interoperability for the short-term)
- Provide compatible environments (e.g. Anaconda) or VM/Docker implementations for cross-OS support.
- Consistent ‘build’ environment/GitHub
- Develop integrated Use-Case scripts for performing end-to-end planetary and earth calibration, mapping, GIS-preparation, and image processing  applications (perhaps building on Python tools like pysis).
- Plan for library integration and sharing (e.g. Camera Models, ALE, geometry, matching, photometry, across In-situ and orbital, ...).
- Support web-based user access to software (cloud services).
- Support integrated PDS archive and format functionality.

**Comment by jlaura** [comment]
I am going to close this. Please see: https://github.com/planetarysoftware/TSC/issues/1
