### ISSUE TITLE
TSC at the PDW

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/TSC#52]
Our last meeting's notes ended with:

> Tuesday, 6.18 @ 7PM. Location TBD. (Then, The Annex?)

Are we all going to be in Flagstaff next Tuesday?  Or do we need to setup a Zoom channel?

**Comment by AndrewAnnex** [comment]
Sounds good to me, last I heard everyone would be there

-Andrew Annex

**Comment by victoronline** [comment]
I’ll be there. 

- victor.silva

**Comment by jlaura** [comment]
Zoom free - the way to be. We can get a location determined Tuesday? Lots of good options.

I am going to close. If someone is remote, we can reopen.

**Comment by rbeyer** [comment]
Someone local needs to make an executive decision about venue.  We need a place to meet where we can all talk and be heard.  If such a place exists, name it.  If not, we can meet at the HCCC or the Drury Inn lounge area first, and then head out afterwards.

**Comment by jessemapel** [comment]
The annex is not a good place for a formal meeting really. If we need a formal meeting space why not at Astro?

**Comment by rbeyer** [comment]
We'll all be down at the HCCC for the poster session.  I figured it was easier to meet locally, then do dinner rather than drive all the way up to the Survey and back.

**Comment by jlaura** [comment]
Dara Thai it is! In the down town, easy to get to etc.

**Comment by michaelaye** [comment]
What time and do we need to reserve?

**Comment by AndrewAnnex** [comment]
Just FYI I had lunch at Dara, but there was another Thai place nearby? Not a big deal, but just thought to mention it.

-Andrew Annex

**Comment by rbeyer** [comment]
We will meet at 7 PM at the dining room tables in the Drury Inn.  There's a skywalk that connects the conference center to the Drury Inn, if you walk underneath the skywalk (or through it) to the Drury Inn, the breakfast dining area is right there.

We'll meet and work through agenda items, and then go to dinner.
